### ISSUE TITLE
Research/refactor browser_name.dart

### ISSUE THREAD

**Issue by bootstraponline** [software-platform/metrics#30]
https://github.com/software-platform/metrics/blob/c8a8a418c4d695ee0f7872678a3b6deed5c334fe/metrics/test_driver/browser_name.dart#L1-L20

**Comment by vova-beloded** [comment]
Because the dart lang has no enums with the custom values, this is the best way to have type safety around the strings, but I’ve made some changes to improve this approach. In case we have to be sure that the BrowserName class won’t be initialized outside this class, I’ve made the default constructor private.

**Comment by bootstraponline** [comment]
@vova-beloded Thank you! Excellent work.
